### ISSUE TITLE
Camera left and right movement occurs at different speed depending on camera pitch value

### ISSUE THREAD

**Issue by raybbian** [kevinsadi/lei3d#32]
I have already implemented a fix to this issue in this commit: https://github.com/kevinsadi/lei3d/commit/852e798f9dbb37836b00c6d4f0ccad547e78ae4f, but waiting for https://github.com/kevinsadi/lei3d/pull/31 to be merged in order to create a pull request.

**Comment by kevinsadi** [comment]
good catch
